### ISSUE TITLE
Create Default Status in seeds.exs

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#101]
# Context

At present we only have _one_ status in our **`Auth`** app: "***verified***"

```sql
dwylauth::DATABASE=> SELECT * FROM status;           
                                                                                                        
id  |   text   |     inserted_at     |     updated_at      | person_id
----+----------+---------------------+---------------------+-----------
  1 | verified | 2020-04-22 17:13:28 | 2020-04-22 17:13:28 |   1
(1 row)
```

This is created by `create_admin/0` in `seeds.exs`:

https://github.com/dwyl/auth/blob/fafc5e059d65de420b4d99bf1d15ac45a3bcda12/priv/repo/seeds.exs#L15-L34

Specifically the line: 

https://github.com/dwyl/auth/blob/fafc5e059d65de420b4d99bf1d15ac45a3bcda12/priv/repo/seeds.exs#L23

We need to have at _least_ 4 `status` entries: `verified`, `active`, `flagged`, `deleted` (soft delete)

In the **`Email`** App we have 5 statuses:

```sql
dwylmail::DATABASE=> select * from status;
 id |       text       |     inserted_at     |     updated_at      | person_id
----+------------------+---------------------+---------------------+-----------
  1 | Opened           | 2020-03-23 14:31:32 | 2020-03-23 14:31:32 |   1
  2 | Pending          | 2020-03-23 14:36:27 | 2020-03-23 14:36:27 |   1
  3 | Sent             | 2020-03-23 14:36:28 | 2020-03-23 14:36:28 |   1
  4 | Bounce Permanent | 2020-03-23 14:37:01 | 2020-03-23 14:37:01 |   1
  5 | Bounce Transient | 2020-04-16 08:56:55 | 2020-04-16 08:56:55 |   1
(5 rows)
```

# Todo

+ [ ] Determine the all different `status` values that are required for our various Apps
  > Note: our plan is to use the _same_ DB for the **`Auth`** and **`Email`** Apps, see: #100
     So having the stautses for both the **`Auth`** and **`Email`** Apps makes sense. 
+ [ ] Create a `.json` file where we can manage the `default` statuses similar to the [`/priv/repo/default_roles.json`](https://github.com/dwyl/auth/blob/87c52d6da8191fcccda3526a84eb21ee4288621c/priv/repo/default_roles.json) 
  > That way the statuses that are common to all apps are version-controlled and easily understandable.
+ [ ] Insert the default statuses using a function in `seeds.exs`, again similar to: [`priv/repo/seeds.exs#L104-L126`](https://github.com/dwyl/auth/blob/87c52d6da8191fcccda3526a84eb21ee4288621c/priv/repo/seeds.exs#L104-L126)

+ [ ] Script ***must*** check for existence of each status ***`before`*** attempting to insert it to **avoid duplicates**!

**Comment by nelsonic** [comment]
Really wish I could get _help_ on this ... feels like something _everyone_ could contribute to. 💭 
I totally _get_ it that this can be perceived as "boring" work ... but it's _necessary_ for thinking about the App(s) we are building ... Anyway, gonna get on with it. 👍

**Comment by nelsonic** [comment]
Script Does what I need:
![image](https://user-images.githubusercontent.com/194400/92512008-0ec8fd00-f206-11ea-9968-2f0438f8f51c.png)

Now I just need to use the **`deleted`** status in #102 ⏳
