### ISSUE TITLE
Implement "Soft Delete" for API Keys

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#106]
At present we have a "**hard**" **`delete`** for all records in our DB which means that when a record is gone, it's gone for _everrrr_! This is fine from a tidying up perspective but it's _terrible_ from a Security Auditing perspective. If we are going to allow _anyone_ to create an API Key for accessing the dwyl App (_e.g: on their `localhost`_) we want some level of accountability. We want people to be able to "soft delete" (_i.e. invalidate an API Key_) so that it can no longer be _used_, but we still want to have a record of it in case we need to do any security auditing. see: https://en.wikipedia.org/wiki/Information_security_audit

# Todo

+ [x] update `delete_apikey/1` to set the **`:status`** of the `apikey` to **`6`** ("***deleted***")
+ [x] Don't show API keys that are "**deleted**".
+ [x] Deal with the fallout from not allowing hard deletes.

**Comment by nelsonic** [comment]
This is working already in the "Reset API Key" function:
![auth-app-reset-api-key](https://user-images.githubusercontent.com/194400/92704893-2d84dc00-f34b-11ea-83d1-0431af7c13ba.gif)
