### ISSUE TITLE
Add app_id to roles schema

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#108]
In order to make RBAC _useful_ we need to be able to create roles for Apps.
And when a **`new` `person`** joins an App, they need to be assigned a role specific to _that_ App.

# Todo

+ [x] Add `app_id` field to `roles` schema.
+ [x] Request to `/approles/:client_id` should return the list of roles as `JSON`
where `:client_id` is the first half of the `AUTH_API_KEY` (_similar to how `auth_plug` handles auth_).
+ [x] List of Roles for an App should include both the app-specific roles 
and "default" roles created by `seeds.exs` #110 
+ [x] Add `app_id` to `conn.assigns.person` so that we know which `app` the person authenticated with. Related: https://github.com/dwyl/auth_plug/issues/24

**Comment by nelsonic** [comment]
At present the roles listing looks like this: http://localhost:4000/roles
![image](https://user-images.githubusercontent.com/194400/92928491-0efc0f00-f437-11ea-844c-ab9854ede2b8.png)

Next: add `app_id` to the table. ⏳

**Comment by nelsonic** [comment]
A non-admin can create a new role for their _own_ App(s):
![image](https://user-images.githubusercontent.com/194400/92938583-a0be4900-f444-11ea-9057-0337ae8ba8ce.png)

Person with **`superadmin`** role can create a role for _any_/_all_ Apps:
![image](https://user-images.githubusercontent.com/194400/92938659-bcc1ea80-f444-11ea-94fd-7d5fc2e4e3cf.png)

Chrome does not allow me to take a screenshot of the whole screen with the select showing all the options so here is the separate screenshot showing all the apps:
![image](https://user-images.githubusercontent.com/194400/92938717-d8c58c00-f444-11ea-9ceb-c916453b7103.png)

**Comment by nelsonic** [comment]
Roles as viewed by Admin: http://localhost:4000/roles (showing two custom roles)
![image](https://user-images.githubusercontent.com/194400/92942723-beda7800-f449-11ea-9d5f-11d8ab2cec86.png)

**Comment by nelsonic** [comment]
Marginally better layout: http://localhost:4000/roles/1/edit
![image](https://user-images.githubusercontent.com/194400/92944060-6ad09300-f44b-11ea-9aea-eac90deb7568.png)

**Comment by nelsonic** [comment]
Added `app_id` to `conn.assigns.person` ✅
