### ISSUE TITLE
Get List of Roles for App 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#110]
In order to allow **_custom_ roles** for any App that uses Auth, we need a way of getting the list of roles that are relevant to that App _once_ during application startup. The list should be cached in memory to speed up in-app role checking. Such that a call to `RBAC.has_role(person, "hotel_guest")` dwyl/rbac#2 should take **_less_ than a _microsecond_** (_zero network latency_).

# Todo

+ [x] Roles should be linked to an App: https://github.com/dwyl/auth/issues/95 > https://github.com/dwyl/auth/issues/108 ✅ 
+ [x] use `AUTH_API_KEY` to request the list of Roles & Permissions relevant to a given App 
  + [x] Response should be a `JSON` `Array` of `Objects` similar to [`default_roles.json`](https://github.com/dwyl/auth/blob/c1f9d3b0e102c04d1e82b509a9550f237232bbc1/priv/repo/default_roles.json) which should be decoded/parsed as a `List` of `Maps` in `Elixir` using [`Jason.decode/2`](https://hexdocs.pm/jason/Jason.html#decode/2) (_which means we will need to add it as a dependency_).
+ [x] cache the List of Roles in memory to avoid any further HTTP requests > https://github.com/dwyl/rbac/pull/7
+ [x] Refresh the list when the app is Re-booted.

**Comment by nelsonic** [comment]
Dummy request already working: http://localhost:4000/approles/:client_id
![image](https://user-images.githubusercontent.com/194400/93002679-94171f00-f530-11ea-9d81-b5da1ebc71d9.png)

Now I _just_ need to work on restricting to the roles of the app via `:client_id` ⏳

**Comment by nelsonic** [comment]
I've _naively_ tried doing the caching of the `approles` list in the `auth_plug` and was immediately  reminded (_obvs in retrospect_) that any function put in a `plug` runs on _each/every_ request. again, obvs.  So instead, we need to run our `GET /approles/:client_id` in a `config.exs` or "startup" script. 

Reading: https://moosecode.nl/blog/where-do-i-put-startup-code-in-elixir

**Comment by nelsonic** [comment]
OK. We have a `get_approles/2` function working in:
https://github.com/dwyl/rbac/blob/e05a58a7c70dcad9bd0350d516d1e01ea7c2d452/lib/rbac.ex#L41-L49

Next we need to _cache_ the list of roles in ETS, going to borrow some code from:
https://github.com/club-soda/club-soda-guide/search?q=ets&unscoped_q=ets

Tomorrow. 😴

**Comment by nelsonic** [comment]
Cache working:
https://github.com/dwyl/rbac/blob/7dcab4458da60fa2371cad05abc3d38278d70db3/lib/rbac.ex#L87-L97
