### ISSUE TITLE
Add :app_id to people_roles + allow people to grant any role for their app(s)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#119]
At present only `superadmin` (`person.id == 1`) can `grant` roles to people.

https://github.com/dwyl/auth/blob/23df8070f7a39e09a70420dbb0ea3f3eb3bcdad9/lib/auth_web/controllers/role_controller.ex#L141-L155

We obviously need the ability for people who own an `app` to be able to grant the role that they created to any `person` who has authenticated with their `app` ...

# Todo

+ [x] Add `:app_id` to `people_roles` schema.
+ [x] Restrict granting a role to the person that _owns_ the App. 
  + [x] Any person should be able to `grant` one of the `default roles` to any person authenticated with _their_ App (_via `auth`_). 

This is related to (but distinct from) restricting access to roles #116

**Comment by nelsonic** [comment]
I still have my editor open for #85 so I'm going to make a quick pass at this now. Wish me luck! 💭

**Comment by nelsonic** [comment]
This issue is complete but will only be enabled once #123 is merged. :shipit:
