### ISSUE TITLE
Allow App Admin to see People (authenticated with their App)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#122]
At present only `superadmin` can view the people authenticated with `auth`. 

![image](https://user-images.githubusercontent.com/194400/93476733-06518000-f8f2-11ea-811d-275c29f2665c.png)

![image](https://user-images.githubusercontent.com/194400/93476773-10737e80-f8f2-11ea-9ff2-ba37f2c3ce15.png)

Obviously this means that **non-admin** cannot _see_ people in order to grant them roles #119 
which kinda limits the functionality of `RBAC` for non-admin people ... 🤦 

So we need to allow non-admin people to _see_ the people who have authenticated with _their_ app but _not_ see the people who have authenticated with other apps. 💭 

# Todo

+ [x] Add `:app_id` to `login_logs` table
+ [x] Log which app a person authenticates for/with in `login_logs` table
+ [x] Select people from this table based on the `app_id` 
+ [x] Display these people in the `/people` (`index`) view
+ [x] Allow `app_admin` to _view_ the `/person/:id` provided that person has authenticated with their app.

**Comment by nelsonic** [comment]
Given that  https://github.com/dwyl/smart-home-auth-server/issues/26 will not be functional without this, I'm working on it _now_. ⏳

**Comment by nelsonic** [comment]
This feature is included in #123 🚀
