### ISSUE TITLE
Potential Conflict in person.id 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#125]
At present we are inserting the **GitHub `profile.id`** as the **`person.id`** when someone authenticates with GitHub.

![image](https://user-images.githubusercontent.com/194400/93663462-1ab38b00-fa60-11ea-8b19-cd68a58bab99.png)

We have an auto-incrementing **`person.id`** for people who register with email+password or Google,
which means that once we have enough people authenticating with their Google account and the auto-increment gets to 200k then the people with those (_early adopter_) GitHub accounts will not be _able_ to authenticate with `auth`. 😕 

We can avoid this potential conflict by creating a `github_id` field on `people` and storing their `github_id` there.
That way the person has an `auth` `person.id` that is unique and a separate `github_id` that allows us to verify their GitHub identity when they authenticate. 

**Note**: GitHub **`username`** cannot be used for this purpose because anyone can _change_ their GitHub `username` ... 🙄 

# Todo

+ [x] Create migration to add `github_id` to `people`  schema.
  + [x] Should be an `integer` and default to `null` in Postgres.
+ [x] Update `auth_controller.ex` to lookup the person by their `github_id` when authenticating with GitHub
+ [x] Update `auth_controller_test.exs` to reflect these changes if required.

**Comment by nelsonic** [comment]
This is a good cheat sheet for Migrations: https://devhints.io/phoenix-migrations
```
mix ecto.gen.migration add_github_id_to_people
```

https://github.com/dwyl/auth/blob/a75e1af10a51e9511ce7353108f24238dfb1809e/priv/repo/migrations/20200928082049_add_github_id_to_people.exs#L6-L10

**Comment by nelsonic** [comment]
Sadly, we get the following error in our GitHub Auth test:
```
     ** (KeyError) key :id not found in: %{access_token: "12345", app_id: 1, avatar_url: "https://avatars3.githubusercontent.com/u/10835816", email: "test@gmail.com", login: "test_user", name: "Testy McTestface"}
```
![image](https://user-images.githubusercontent.com/194400/94411948-1b8ba180-0171-11eb-9587-098afe8e4965.png)

This is because the underlying https://github.com/dwyl/elixir-auth-github does not have an `id` field in the mock (`@valid_body` data) which we use in our tests. 🙄 

Going to add this now. ⏳

**Comment by nelsonic** [comment]
Included in #123 :shipit:
