### ISSUE TITLE
Rework login_logs to be general purpose request log 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#126]
At present we have a **`login_logs`** schema (_which is not being used see: #67 ..._):

https://github.com/dwyl/auth/blob/fde3b661e568bb23e01238abada9fae02084a823/lib/auth/login_log.ex#L9-L15

It already has the beginnings of a useful schema from the perspective of logging authentication attempts. But given that no data is being written to the table, and on further reflection, I think we can use it as a general purpose request log that can log both successful/failed auth attempts ***and*** subsequent requests. 

# Todo

## Part 1: Re-purpose `login_logs` > `logs`

+ [x] Rename `login_logs` to simply `logs`
+ [x] Add the following fields:
  + [x] `:app_id` - the app for which the request was made (_`Integer`_)
  + [x] `:request_path` - the path requested by the client (_should be encrypted_)
  + [x] `:status` - references `status` table (_we will use HTTP status codes in our logs_).
    + [x] Add HTTP Status Codes to [`statuses.json`](https://github.com/dwyl/auth/blob/master/priv/repo/statuses.json)
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

+ [x] Move `ip_address` to  `user_agent` table to reduce duplicate data.
+ [x] Add `ua` (`useragent.id`) to `conn.assigns..ua` so we insert the `useragent` _once_ and then assign the `id` to the request so we don't need to keep looking it up on subsequent requests.

## Part 2: Write Tests and Corresponding **`Auth.Log`** Functions

+ [x] Create tests that insert records into:
  + [x] `user_agent` (_while I'm not so sure about the [name](https://github.com/dwyl/app/issues/33) of this table, at least it's clear what it is ..._) 
  + [x] `log` via **`Auth.Log.info/2`** and **`Auth.Log.error/2`** functions.
    + [x] **`Auth.Log.info/2`** should insert a row into the `log` and use `Logger.info` to log.
    + [x] **`Auth.Log.error/2`** Should use `Logger.error` to publish the log message to `sdout`

## Part 3: Use **`info/2`** and **`error/2`** in `AuthController.ex`

+ [x] Log both successful and failed login attempts using **`Auth.Log.info/2`** and **`Auth.Log.error/2`** respectively.

**Comment by nelsonic** [comment]
I've got this working _mostly_ the way I _think_ we need now ... 💭 
Just going to add `msg` to the `logs` schema and then I think we can ship this!

**Comment by nelsonic** [comment]
Done. ✅ 
We now have a general purpose logging interface that allows us to log anything from anywhere. 🎄 
Included in PR #123 :shipit:

**Comment by nelsonic** [comment]
Example of logs including both success and failure:
![image](https://user-images.githubusercontent.com/194400/94157343-09f88000-fe79-11ea-8512-c4cfee6baf9f.png)
