### ISSUE TITLE
Friendly/Helpful Error Page

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#128]
At present if an App using `auth_plug` redirects to auth with an invalid `auth_client_id` (_the name of `client_id` in a url_) the person attempting to authenticate will see this unfriendly error page:
![image](https://user-images.githubusercontent.com/194400/94489164-e5cfd280-01db-11eb-99e2-26ccc77a899f.png)

This is obviously undesirable. Let's create a _friendly/helpful_ error page. 

# Todo

+ [x] Create Reusable error template (HTML) 
  + [x] Borrow from: https://github.com/dwyl/hapi-error/blob/master/example/error_template.html
![image](https://user-images.githubusercontent.com/194400/94492115-7826a500-01e1-11eb-8058-fdcbe7ec673a.png)

+ [x] Invoke the reusable template from our existing error handler functions:

https://github.com/dwyl/auth/blob/fde3b661e568bb23e01238abada9fae02084a823/lib/auth_web/controllers/auth_controller.ex#L193-L207

Relevant to / required by: #129

**Comment by nelsonic** [comment]
Rendering `404.html.eex` template in `AuthWeb.AuthController.not_found/2`. ✅ 

Created role:
![image](https://user-images.githubusercontent.com/194400/94610163-c4342100-0297-11eb-9c68-6f1b0b6f1a1e.png)

But role is not visible to person who does not "own" it:
![image](https://user-images.githubusercontent.com/194400/94610321-08272600-0298-11eb-99ba-b7571147b0bb.png)

**Comment by nelsonic** [comment]
reuse `404.html.eex` template in generic `error/3` function
which is then called by `unathorized/2` and `not_found/2`:
https://github.com/dwyl/auth/blob/a53fa866c2979364596c9ba9541622a96977ec60/lib/auth_web/controllers/auth_controller.ex#L177-L192

**Comment by nelsonic** [comment]
Included in #123 📦

**Comment by nelsonic** [comment]
Very happy for anyone else to improve this in the future. 
But for now it does what we need. ✅
