### ISSUE TITLE
Automatically Reject Auth Request with Invalid auth_client_id

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#129]
At present if an App redirects to auth with an invalid `auth_client_id` (_the name of `client_id` in a url_) 
https://dwylauth.herokuapp.com/?referer=http://localhost:4000/admin&auth_client_id=invalid
![image](https://user-images.githubusercontent.com/194400/94487980-bb7d1580-01d9-11eb-9065-9ff5551a9c19.png)

# Context

While testing Optional Auth for https://github.com/dwyl/auth_plug/issues/27 which we need for https://github.com/dwyl/auth/issues/69, I noticed that if the `AUTH_API_KEY` is invalid, I still see an Auth Page and I'm allowed to authenticate ... but then after authenticating I see the `401` error:
![image](https://user-images.githubusercontent.com/194400/94489164-e5cfd280-01db-11eb-99e2-26ccc77a899f.png)

This is an obvious UX Fail. So let's fix it!

# Todo

+ [x] Start by `Logging` all attempts to decrypt `auth_client_id` to see if there are errors.
+ [x] Reject a request with an invalid `auth_client_id` (`client_id`) as early as possible to avoid the person going through OAuth2 with a Provider only to have their request rejected later ...
+ [x] Definitely need a **_Friendly_ Error Page** at this point #128
+ [x] Write tests for this rejected request (_should be easy_)

**Comment by nelsonic** [comment]
OK, this is _affecting_ my progress now and it's a **_horrible_ experience**.
![image](https://user-images.githubusercontent.com/194400/94989245-31330980-056b-11eb-9f8e-cc798c5a2d82.png)

![image](https://user-images.githubusercontent.com/194400/94989258-3e4ff880-056b-11eb-9d43-d84ff0640b69.png)

Going to switch to addressing this _now_!

**Comment by nelsonic** [comment]
Ok, so after reading through the code, I spotted that the `get_referer/1` function in `auth_controller.ex` was getting the HTTP referrer from the Request Headers but but then _not_ appending the `auth_client_id`:

https://github.com/dwyl/auth/blob/ee2ef5f97014e2eac8b8af05975dee664dfb60d2/lib/auth_web/controllers/auth_controller.ex#L97-L101 

Which means that the `client_id` is not appended to either of the OAuth URLs,
which means that when once the person has _successfully_ authenticated,
Auth app thinks there is no `client_id` to lookup the `client_secret` to sign the `JWT`.
So the request fails.

**Comment by nelsonic** [comment]
The reason the tests failed on the last commit was that `Auth.Log.info/2` was called with a _nested_ Map:
https://travis-ci.com/github/dwyl/auth/builds/187968700#L623
![image](https://user-images.githubusercontent.com/194400/95012757-1035eb80-0633-11eb-9380-aa97399e0ae5.png)

So I went on a little detour to create [`Useful.flatten_map/1`](https://github.com/dwyl/useful#flatten_map1) https://github.com/dwyl/useful/issues/2 which is now in-use.

**Comment by nelsonic** [comment]
Fixed / included in #134 ✅
