### ISSUE TITLE
[Epic] Authentication in the dwyl App?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#13]
Currently we are _assuming_ people want to Authenticate into the dwyl app using Email & Password.
We have not collected any _data_ on this so we don't _know_ what people want/expect.

### Todo

+ [x] Allow people to ***register*** using their **email address**. #63 
  + [x] Build simplest possible registration form requiring ***only*** an **email address**. https://github.com/dwyl/auth/issues/14
+ [x] ***Automatically log them in*** to the app so they can start using it _immediately_ (_if their email address is valid_)
+ [x] send them a `"please verify your email address"` email as soon as they enter a valid email address. #63 
+ [x]  When they click (_or copy-paste_) the link to ***verify email address*** (_which we sent to their email address_) we should ask them to record a few more details starting with a ***password*** 

### To Discuss

+ [x] Should we _prevent_ "_unverified_" people from using certain parts of the app/site until they have successfully verified their email address?
+ [x] What other details do we want people to provide when they are registering to use the app? e.g:
  + [x] First Name
  + [x] Last Name
  + [x] How did you hear about dwyl app?

Authenticating with [Google](https://github.com/dwyl/elixir-auth-google), [~~Facebook~~](https://github.com/dwyl/learn-react/issues/23#issuecomment-269863769) or [GitHub](https://github.com/dwyl/elixir-auth-github) could be an option depending on the use-case.

Please share your thoughts on which 3rd Party services _you_ would like to login with 
and which ones you have used in other apps or websites.

**Comment by nelsonic** [comment]
Login With ... https://www.google.co.uk/search?q=login+with&tbm=isch

**Comment by nelsonic** [comment]
This is shipped to: https://dwylauth.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/81959334-31a42580-9607-11ea-9ab9-5b3c5afb7443.png)

By using a _separate_ service we are able to enhance privacy/security. 🔐
