### ISSUE TITLE
Update Project to Elixir v1.12

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#145]
At present we are seeing the following error:
```
** (Mix) You're trying to run :auth on Elixir v1.11.2 but it has declared in its mix.exs file it supports only Elixir ~> 1.10.4
```

This is because our `mix.exs` file specifies `1.10.4`:

https://github.com/dwyl/auth/blob/5d044246c6055e4dc2f0797150ad68729064430b/mix.exs#L8

Same in `elixir_buildpack.config`:

https://github.com/dwyl/auth/blob/5d044246c6055e4dc2f0797150ad68729064430b/elixir_buildpack.config#L2

Meanwhile people running a _later_ version of Elixir e.g. `Elixir 1.11.2` sees the error. 

**`José`** 👑  published `v1.12.0-rc.0` yesterday 🎉  https://github.com/elixir-lang/elixir/releases so we might as well go for that. 

# Todo

+ [ ] Update `mix.exs` to latest Elixir version
+ [ ] Update `.travis.yml` to latest Elixir
+ [ ] Update `elixir_buildpack.config` (the version used on Heroku)

**Comment by nelsonic** [comment]
`1.12` released today https://news.ycombinator.com/item?id=27206656 🎉

**Comment by nelsonic** [comment]
Updated to latest:
```
elixir -v
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

**Comment by nelsonic** [comment]
Next error to resolve: #146
