### ISSUE TITLE
Setup Dev Version of Auth Heroku App > authdev.herokuapp.com

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#161]
We recently deployed our "Hits" App to Fly.io as a test: https://github.com/dwyl/hits/pull/128 it's working very well. 🚀 
But we still want to use Heroku for "Dev" and "Test" versions of our Apps because they still have a better interface/UX.

One feature of Heroku (_which is a significantly more "mature" platform-as-a-service_) that I have found particularly useful in the past is "**_Review_ Apps**" which are _temporary_ instances of your App created to test a specific feature/pull request.

# Todo

+ [x] Setup Review Apps for Dwyl Auth

Relevant Reading:
+ [x] https://devcenter.heroku.com/articles/github-integration-review-apps
+ [x] https://devcenter.heroku.com/articles/pipelines

**Comment by nelsonic** [comment]
https://dashboard.heroku.com/pipelines/8ae3dbca-f5fc-4641-99a7-7b9adff382c7
![image](https://user-images.githubusercontent.com/194400/141365665-0b3d79a5-18f8-4929-a155-e19a1d2acc55.png)

After further investigation, it's clear that we will have to _manually_ setup each Review App because both GitHub and Google OAuth setup requires a URL. i.e. we cannot re-use `GOOGLE_CLIENT_ID` / `GOOGLE_CLIENT_SECRET` from one App to another because the URL changes each time ... 🙄 

So basically, unless we want to go through _all_ the steps to create a Google / GitHub App each time for the review app, I think this is a bit of a non-starter. 

So I've done the next-best-thing and created a new app: https://authdev.herokuapp.com/

https://dashboard.heroku.com/apps/authdev/deploy/github
![image](https://user-images.githubusercontent.com/194400/141366168-d1c9ac61-76b9-4a53-9f7c-112716004287.png)


But it's not yet working ...
![image](https://user-images.githubusercontent.com/194400/141366769-f83e69ca-fd49-4065-9092-d518d09dcd10.png)

Need to run the `mix ecto.setup` in the `Procfile`, similar to: 
https://github.com/dwyl/phoenix-chat-example/blob/1c16c819ef1af139f22c2b2d488a1c4fd5e77cdf/Procfile#L1

**Comment by nelsonic** [comment]
Had to run the `seeds` manually:

```
heroku run 'POOL_SIZE=2 mix run seeds'
```

**Comment by nelsonic** [comment]
Works: https://authdev.herokuapp.com/

![image](https://user-images.githubusercontent.com/194400/141369675-21fd2211-136d-462d-aa62-e1cbf53b6d5f.png)

![image](https://user-images.githubusercontent.com/194400/141369710-3797bff8-af70-4284-8b16-5a8dab0cfdb8.png)

![image](https://user-images.githubusercontent.com/194400/141369746-95191378-f1a3-4298-a937-37729d5cb7a0.png)

We can use and _break_ this version of the app to our heart's content. 🔨

**Comment by nelsonic** [comment]
Using this to test PR #159 👨‍💻

**Comment by nelsonic** [comment]
@iteles & @SimonLab you both have access to this new App if you need: https://dashboard.heroku.com/apps/authdev 👍
