### ISSUE TITLE
Simplify/Split auth_controller

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#168]
As noted by @SimonLab in the PR https://github.com/dwyl/auth/pull/159 the **auth_controller** is _way_ too big.
The file is currently **507** lines. This is *far* too long. 

https://github.com/dwyl/auth/blob/76c0161d038e3d8c3840097c37e03c1d967f6b67/lib/auth_web/controllers/auth_controller.ex#L497-L507

# Todo

+ [ ] Review the file and determine if we can extract generic/helper functions
+ [ ] Extract email+password related auth code into its own file, filename at your discretion.
+ [ ] Remove OAuth (Google / GitHub) related code

**Comment by nelsonic** [comment]
Gonna do this as part of #207 👌
