### ISSUE TITLE
seeds.exs ... tidy/improve initialising data into auth db

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#174]
# The "on-boarding" for the `auth` App _suuuuuuuuucks_! 😢 

`while` attempting to `fly deploy` the `auth` app to Fly.io we noted that the `seeds.exs` file was not being executed: https://github.com/dwyl/auth/issues/172#issuecomment-1005194147  this means there is no `app` created in the DB:

![no-data-in-auth-db](https://user-images.githubusercontent.com/194400/148127661-2aa97a14-0f5c-4401-a331-7bd43e78e2ed.png)

so the home page does not even render. 💔 

![image](https://user-images.githubusercontent.com/194400/148198886-5b9ed26e-c1cc-40dc-b9b9-15dffaaf68ad.png)

Re-reading the [`/priv/repo/seeds.exs`](https://github.com/dwyl/auth/blob/6466f8b212a40229fbec6e7398f33f2ecfa22a8c/priv/repo/seeds.exs) file I can see the intent ... 
but I'm _embarrassed_ by how messy it is and I _apologise_ to anyone who has attempted to read/grok it ... 🤦‍♂️ 
**100% mea culpa**! Didn't think the `seeds.exs` code was going to be looked at very often so didn't invest enough time in it. ⏳ 

Related to: "Updated instructions needed ..." https://github.com/dwyl/auth/issues/157, "More clarity ..." https://github.com/dwyl/auth/issues/149 and "How to resolve `auth_plug` dependency https://github.com/dwyl/auth/issues/170

# Possible approaches to solve this

My initial assessment is that we can approach solving this in (_at least_) **4 different ways**, in **order** of **_increasing_ effort/time**:

1.  **Re-org** & **add comments** to the `seeds.exs` file which is currently only **147 lines** of code.
> The issue with this first approach, as noted in https://github.com/dwyl/auth/issues/172#issuecomment-1005537094 is that the /priv/repo/seeds.exs` file does not appear to be available on Fly.io once the release is created/compiled. 
2. ***Re-write*** it from scratch with a fresh pair of eyes and move it to `/lib` where it will be executable by the `mix release`
3. **Create** something **`new`** that outputs raw SQL that we can run directly on the DB
https://stackoverflow.com/questions/36770956/how-can-i-see-the-raw-sql-generated-for-an-ecto-query
[` Ecto.Adapters.SQL.to_sql/3`](https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#to_sql/3)
4. **Create** a "**Setup & Status**" wizard/screen that informs the **`superadmin`** of the status of their `auth` instance. 
  i. Creates the "default" app if it does not already exist. This will only happen once. >> https://github.com/dwyl/auth/issues/176
  ii. Displays the `AUTH_API_KEY` for the default app so it can be exported as an environment variable
  iii. Once the `AUTH_API_KEY` environment variable is set, display this detail on the "status" page.
  iv. Check all the other environment variables are defined so that the person setting up the `auth` app _knows_ the status.

> This 4<sup>th</sup> Option/approach would help with the `auth_plug` dependency https://github.com/dwyl/auth/issues/170

# Todo

+ [x] **Discuss & _Decide_** which approach we are going to take to fixing the `seeds.exs` problem in both the short-term and longer term. 
+ [x] **Implement** the chosen solution.
  + [x] **Seeding data** should be **idempodent** https://en.wikipedia.org/wiki/Idempotence#Computer_science_meaning (obvs). 

+ [x] **_Test_ it** on `localhost` and Heroku
+ [ ] Test by deploying to Fly.io ... https://github.com/dwyl/auth/issues/172

> Note: I've applied **`priority-1`** and **`BLOCKED`** to this because it is currently blocking deployment to Fly.io 🔥 
> I've also created **`tech-debt`** label in _this_ repo and proposed we add it to the **`labels`** repo: https://github.com/dwyl/labels/issues/101

**Comment by th0mas** [comment]
I'm in favour of option two. Some comments I have to make this easier on others setting up the app:

1. I don't like being having to re-start the application to set an `AUTH_API_KEY` - if we can aim for "1-click" deploy, we should.
i. Regarding this, it might be worth adding a new initialisation function to `AuthPlug` that can take a signing key as a parameter, not as an environment variable. This shouldn't be a breaking change, as the default would still be to rely on the environment variable for configuration.
2. We could add a line to the `Auth.Release.migrate/0`  function that checks to see if the default app is initialised, this way it would be transparent to the person deploying the application. 
i. This would need some further discussion as we would need to make it clear to the person deploying how to change the default initialisation values (e.g. the role names) if they wanted

**Comment by nelsonic** [comment]
Great suggestions. Totally agree. 🙌 
If you have time to help with this, please do. (Check your Signal messages ...) 🙏

**Comment by nelsonic** [comment]
Going to try and make a start on this. 🤞 ⏳

**Comment by nelsonic** [comment]
Made an attempt to move `seeds.exs` to `init.ex` and added a few tests+docs. Please see: https://github.com/dwyl/auth/pull/175 (Thanks!)

**Comment by SimonLab** [comment]
PR #175 is now merged into main

**Comment by nelsonic** [comment]
@SimonLab thanks for reviewing/merging. 🙌 

With `lib/auth/init/init.ex` now available, I've been trying to run it in `lib/auth/release.ex` but cannot get past the error:

##### `** (RuntimeError) could not lookup Ecto repo Auth.Repo because it was not started or it does not exist`

As reported in: https://github.com/dwyl/auth/issues/172#issuecomment-1026307390

So rather than banging my head against the wall (_I've spent **hours googling** and reading forum/blog posts ..._) 🤦‍♂️ 
I'm going got build a "status" page as per **Option 4** in the OP above. ⬆️ 
Haven't quite figured out everything that is required for this ... but will take a look at it tonight. 🤞

**Comment by nelsonic** [comment]
Tested the new `init.ex` (invoked by `seeds.exs`) script on Fly.io: https://github.com/dwyl/auth/issues/176#issuecomment-1030963217 https://authprod.fly.dev/init

![image](https://user-images.githubusercontent.com/194400/152709372-6496b83d-4a8a-4a14-ba5f-f41645fe8c1c.png)

Works as expected. ✅ 
Closing.
