### ISSUE TITLE
Images not appearing on auth.dwyl.com

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#178]
Just tried to view the `init` page: https://auth.dwyl.com/init and noticed that the images are "broken":

![image](https://user-images.githubusercontent.com/194400/153305674-f5133896-f7fa-4a8d-b6ef-fbe249657b12.png)

they are `404`: https://auth.dwyl.com/images/true.png
![image](https://user-images.githubusercontent.com/194400/153305753-3274e823-8433-4630-9b4d-bd923bf785e9.png)

https://github.com/dwyl/auth/tree/main/assets/static/images
![image](https://user-images.githubusercontent.com/194400/153305827-4808413e-9d0f-4073-9bca-b2be86bfc8cd.png)

https://github.com/dwyl/auth/blob/main/assets/static/images/true.png
![image](https://user-images.githubusercontent.com/194400/153305895-d76e49b8-6f85-4084-ad94-24d227589fc8.png)

But they aren't being deployed to Fly.io ...

# Todo

+ [ ] investigate why assets are not being deployed on Fly.io
+ [x] remedy the problem with a PR #179 
+ [ ] confirm it's fixed once the PR is merged

**Comment by nelsonic** [comment]
Just using the raw images on GitHub as my CDN: https://raw.githubusercontent.com/dwyl/auth/main/assets/static/images/true.png
https://raw.githubusercontent.com/dwyl/auth/main/assets/static/images/false.png

**Comment by nelsonic** [comment]
Working: https://auth.dwyl.com/init ✅ 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/194400/155973383-4a6013c7-9b24-4412-b45a-934cd9a89868.png">

Thanks for reviewing and merging @SimonLab 🙌
