### ISSUE TITLE
Auth Application Error dwylauth.herokuapp.com

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#180]
When revisiting the LiveView Chat Example:  https://github.com/dwyl/phoenix-liveview-chat-example
The app works fine:  https://liveview-chat-example.herokuapp.com/

![image](https://user-images.githubusercontent.com/194400/155111347-300298ee-b869-401d-9e74-c7a8b88e84ad.png)

When I attempt to use the Login button in the top nav:

![image](https://user-images.githubusercontent.com/194400/155108215-e5c96c5d-d0e2-4b17-b070-4e828aca9f60.png)

I see the following Application error: 

![image](https://user-images.githubusercontent.com/194400/155107981-0647b3e3-bea7-430c-b337-bf0589cfb330.png)

The error persists on both the home https://dwylauth.herokuapp.com/ and the init page https://dwylauth.herokuapp.com/init

![image](https://user-images.githubusercontent.com/194400/155108457-c756402a-6773-44b0-a568-1df09ad27bcd.png)

# Todo

+ [ ] Investigate why the Heroku instance of the Auth App dwylauth.herokuapp.com is not working
+ [ ] Get it working again!
+ [ ] Create PR if necessary

**Comment by nelsonic** [comment]
Just checked and it's the same story on https://authdev.herokuapp.com/ ... 🤦‍♂️ 
![image](https://user-images.githubusercontent.com/194400/155111980-a9bee69b-8a64-4b94-8603-dd21cda2a300.png)

So I've obviously broken something recently. 🤦 
Will take a look during my lunch break from work-work. ⏳

**Comment by nelsonic** [comment]
Viewing the logs: https://dashboard.heroku.com/apps/dwylauth/logs we see there's a Postgres Error:
![image](https://user-images.githubusercontent.com/194400/155116429-45cdec59-bcd0-4992-b5db-9a0467bddb40.png)

I think I know why ... I changed some of the DB constraints for the Fly.io deployment (because we don't need certain constraints on Auth ...) see `migrations` in https://github.com/dwyl/auth/pull/173/files ...

**Comment by nelsonic** [comment]
Given that we aren't using `authdev` for anything important, 
I reset the database to confirm that deploying a _fresh_ app to Heroku works ... 

Then attempted to run:
```sh
heroku run "POOL_SIZE=2 mix ecto.migrate" --app=authdev
```

But got the following error:

```
Running POOL_SIZE=2 mix ecto.migrate on ⬢ authdev... up, run.7060 (Free)

20:05:21.753 [error] Postgrex.Protocol (#PID<0.367.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "54.76.240.159", SSL off

20:05:21.753 [error] Postgrex.Protocol (#PID<0.368.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "54.76.240.159", SSL off

20:05:22.832 [error] Postgrex.Protocol (#PID<0.368.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "54.76.240.159", SSL off

20:05:24.537 [error] Postgrex.Protocol (#PID<0.367.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "54.76.240.159", SSL off

20:05:24.541 [error] Postgrex.Protocol (#PID<0.368.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "54.76.240.159", SSL off

20:05:24.682 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :auth, Auth.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2984ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:678: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:504: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    (ecto_sql 3.7.1) lib/mix/tasks/ecto.migrate.ex:138: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
```

It appears that the The database does not exist ...

Tried:

```
heroku run "POOL_SIZE=2 mix ecto.create" --app=authdev
```

```
20:09:00.957 [error] GenServer #PID<0.367.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "54.220.238.200", SSL off
    (db_connection 2.4.1) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

20:09:00.974 [error] GenServer #PID<0.374.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "54.220.238.200", SSL off
    (db_connection 2.4.1) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Auth.Repo couldn't be created: killed
```

Side-note: the Heroku Web UI is _painfully_ slow today ... I'm consistently seeing these blank (below the fold) screens:

![image](https://user-images.githubusercontent.com/194400/155360004-572c879d-fc1e-4dbb-a542-140c5afe770d.png)

Need to refresh my memory on:

```
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host
```

"Postgrex.Error no pg_hba.conf entry for host" ...

https://stackoverflow.com/questions/31663674/postgrex-no-pg-hba-conf-entry-for-host-xxx-xxx-xxx-xxx

Suggests that we need to add some config to make `ssl: true` on Heroku. 

Added the config on my `localhost` and pushed it to Heroku and it appears to have fixed the issue:

![image](https://user-images.githubusercontent.com/194400/155365473-98746fc8-a132-4f96-8cea-c70b5990fa4b.png)

Now this is what I see: https://authdev.herokuapp.com/init
![image](https://user-images.githubusercontent.com/194400/155365535-addc60cd-d1cd-4278-a375-9345c44da415.png)

Which is _exactly_ why I wanted this page! 🎉 

Went to the settings page: https://dashboard.heroku.com/apps/authdev/settings
added `AUTH_URL=authdev.herokuapp.com` 

![image](https://user-images.githubusercontent.com/194400/155365815-5b204917-0106-41de-8bf9-dcbe8973f6b3.png)


Restart all dynos:

![image](https://user-images.githubusercontent.com/194400/155366022-806a4212-9b5b-441b-b1e7-ec8a0429017f.png)


Init looks good now: https://authdev.herokuapp.com/init
![image](https://user-images.githubusercontent.com/194400/155366172-b838afad-f681-457a-8fcc-ce066bb9d1f6.png)

Boom! 💥  working again! https://authdev.herokuapp.com/

![image](https://user-images.githubusercontent.com/194400/155366241-3321da63-bd8b-4f64-8f5f-768ebac7b286.png)

Pushed the same changes to `dwylauth` and they work without resetting the DB. 🚀 

https://dwylauth.herokuapp.com/people
![image](https://user-images.githubusercontent.com/194400/155367474-af2b1747-7af4-4964-8647-8c803a56cd71.png)

Included in PR: #179 ✅  (Not urgent as both Heroku instances are fixed now!)
