### ISSUE TITLE
Groups UI/UX

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#232]
This issue will help us track the features for creating, managing, adding and removing `people` from `groups`.
The whole **`groups`** experience should _feel_ like a **Single Page App** (SPA).
It should be Mobile-first but still look good on _any_ Screen. 

Managing groups will be an _infrequent_ occurrence. 

# Story

As a **`person`** focussed on making the most of my life,
I want to **create** a **`group`** 
So that I can ***collaborate*** with (one or more) other **`people`**

# Todo

+ [ ] Create `LiveView` for Groups. **`needs-ui`** 
+ [ ] `group.name` should be displayed as [`text-4xl`](https://tailwindcss.com/docs/font-size) as page header
  + [ ] Should be _editable_ without leaving the page same as `item.text` is in **`MVP`**.
+ [ ] `group.desc` should be displayed as `text-xl` and switch to `<input>` when edited. 
+ [ ] `group.kind` dropdown list populated by `Enum` select from pre-defined list.
  + [ ] Starting list: 
```elixir
field :status, Ecto.Enum, values: [family: 1, friends: 2, personal: 3, sports: 4, work: 5, church: 6]
```
  + [ ] The `kind` dropdown will  be ***alphabetical***. Later on it could be based on a frequency heuristic 
  i.e: the `kind` that _most_ people use most often will appear first in the suggested list. 
  + [ ] Adding to the list of "kinds" will be via updating the `Enum` for now. i.e. `code`
    Assuming this will be OK given that these won't change or be added very often. prove me wrong. 
+ [ ] Lookup/invite `people` to `group` by `person.name` or `person.email` 
+ [ ] Show list of all `people` you have a connection with as your "pool" of potential `group_members`
+ [ ] Remove a `person` from the group.

**Comment by nelsonic** [comment]
Rough Sketch:
![0B52AFD7-F6A2-4413-8957-101008501EAD](https://user-images.githubusercontent.com/194400/199695684-f0d80c54-748a-4512-868a-dc93a53badd3.jpeg)
