### ISSUE TITLE
Auth: Deploy Demo Version to Fly.io

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#246]
In light of the Heroku (Salesforce bean-counter) penny-pinching https://github.com/dwyl/learn-heroku/issues/52 🤦‍♂️ 
we are migrating all our demo/example apps off the platform. ⏳ 

# Todo

+ [x] **Create `new` Org** on Fly.io: **`dwyl-authdemo`** 🫂 
+ [x] **Create `new` App** on Fly.io: **`authdemo.fly.dev`** 🍏 
+ [x] **Create** corresponding **`Postgres`** instance **`authdemo-db`** and attach it to the App. 🔋 
+ [x] **Create** New **OAuth** Apps on: 
  + [x] **`GitHub`**: https://github.com/dwyl/elixir-auth-github/blob/main/create-github-app-guide.md
  + [x] **`Google`**: https://github.com/dwyl/elixir-auth-google/blob/main/create-google-app-guide.md
+ [x] **_Deploy_** Latest version of **`main`** to the new Fly.io App 🚀 
+ [x] **_Test_** the **`authdemo`** app ... 🧪 
+ [x] **_Use_** it in the other **Demo/Example** Apps e.g: https://github.com/dwyl/phoenix-chat-example/pull/120 🧑‍💻 
+ [x] ***Document*** everything so others can follow. 📝 

I _estimate_ that this will take me/us **`~T1h`** ... ⌛ 
But only cause I've done this before and know the "quirks" ... 🙄 
And worked through them in: #172 :shipit: 

My objective is to improve the docs in the `README.md` to the point where _anyone_ could follow them and deploy their own instance of **`auth`** in **`~T25m`**. 🤞

**Comment by nelsonic** [comment]
Org created: https://fly.io/dashboard/dwyl-authdemo ✅ 
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/194400/201662443-5226c39f-eadd-4ee7-9bc8-2518746e450f.png">

Everyone invited. ✉️ 📥

**Comment by nelsonic** [comment]
Picking this up _now_ cause I really want to ***unblock*** the Phoenix Chat PR: 
https://github.com/dwyl/phoenix-chat-example/pull/120 `<|` https://github.com/dwyl/phoenix-chat-example/issues/54

**Comment by nelsonic** [comment]
Deployed demo version to Fly.io: https://authdemo.fly.dev/init glad I wrote this init page to check status of the Auth App:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/194400/201881510-2ce32a63-d105-4651-90f0-9b530902f675.png">

Going to extract _some_ of the Env Vars from Heroku Demo App: https://github.com/dwyl/learn-heroku/issues/35
And update the **`GitHub`** and **`Google`** Apps URL to this new one. ⏳

**Comment by nelsonic** [comment]
Next: https://github.com/organizations/dwyl/settings/applications/1275498

**Comment by nelsonic** [comment]
https://dashboard.heroku.com/apps/dwylauth/settings

**Comment by nelsonic** [comment]
https://github.com/dwyl/elixir-auth-google/blob/main/create-google-app-guide.md

**Comment by nelsonic** [comment]
Working with Google:

![image](https://user-images.githubusercontent.com/194400/202262407-8be46855-ce7b-4e9b-8a62-570a62d3cde2.png)

🎉

**Comment by nelsonic** [comment]
Deployment docs are still current. ✅

**Comment by nelsonic** [comment]
Gone! 👋 
![image](https://user-images.githubusercontent.com/194400/202263976-57eff0df-b8ae-4763-af39-c201ec59a521.png)

**Comment by nelsonic** [comment]
https://fly.io/dashboard/dwyl-authdemo has **`$25`** credit in case the Fly.io crew decide to charge us. 💰 
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/194400/202421475-1e81ebc2-46ba-4670-ae4a-5b02c909feaf.png">

_Very_ happy to pay a few $$'s/month for this awesome service. 😍
