### ISSUE TITLE
Chore: Update the `people.email` to use `Fields.EmailEncrypted`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#285]
As noted in https://github.com/dwyl/auth/issues/284 sadly, by `default` the `mix phx.gen.auth` generator 
does not setup any _protection_ for personal data in the database. 😢 
Email addresses are stored as `plaintext`: 

![mix-phx-gen-auth-people-table-email-plaintext](https://user-images.githubusercontent.com/194400/223880353-98597d83-cb9c-424d-bcb0-2121ecd743c0.png)

Similarly the `people_tokens` table stores `email` addresses as **`plaintext`** in the `sent_to` column:

![people_token-email-plaintext](https://user-images.githubusercontent.com/194400/223948397-6984b456-8612-492b-bb79-84442c8b4241.png)

This is **_obviously_ undesirable**. 🙃 
This is a privacy/security issue waiting to become a scandal!

# Todo

+ [ ] Re-add `fields` to the newly re-created `auth` (`Phoenix 1.7`) app
+ [ ] Update the `people` and `people_tokens` schemas to use [`Fields.EmailEncrypted`](https://hexdocs.pm/fields/Fields.EmailEncrypted.html) 
+ [ ] Update tests as required

This shouldn't take very long but allocating `T2h` to allow for documenting the steps

**Comment by nelsonic** [comment]
Getting the following error:
```sh
15:06:13.691 [info] alter table people
** (Postgrex.Error) ERROR 42804 (datatype_mismatch) column "email" cannot be cast automatically to type bytea

    hint: You might need to specify "USING email::bytea".
```

**Comment by nelsonic** [comment]
Sadly, having the `person.email` and `person_tokens.sent_to`  in `plaintext` is relied upon by the following query:

https://github.com/dwyl/auth/blob/da0af7ee702c278714b47f92045edce4adad542a/lib/auth/accounts/person_token.ex#L110-L129

I don't see us using this function in our `auth` implementation 
because this is the flow/journey where people click on a link in an email to verify their email address
and we are _definitely_ not doing email verification with links. 

see: https://github.com/dwyl/auth/issues/223#issuecomment-1426810316

So I'm going to explore removing this function and seeing what the ramifications are ... 💭

**Comment by nelsonic** [comment]
Following the changes made in: https://github.com/dwyl/auth/pull/231/commits/2bbba99c7057f0d2943dd8327be52ccf1a1bd58c

If we now run a query to view the data in the `people` table:
```sql
SELECT id, email, inserted_at FROM people;
```
We see that the `email` is now a binary blob 
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/194400/224109679-0084ae9d-a1e8-48f2-a083-94aff46d7137.png">

Registration and Login still works as expected:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/194400/224111036-7a4e5764-8966-4b97-aaea-515c8e3b7fd4.png">

But now the personal data captured in registration is stored **`encrypted`** at rest the way it should be. 🔐

**Comment by nelsonic** [comment]
captured in: https://dwyl.github.io/book/auth/09-encrypt-data.html
