### ISSUE TITLE
[Epic] Session Management

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#30]
# Context

People _expect_ that "Login" (_Authentication / Authorisation_) "**just _works_** ™".
_Nobody_ wants to have to _re_-authenticate _each_ time they use a Web App<sup>1</sup>.
Being forced to re-authenticate creates usage _friction_ and in some cases _abandonment_. 
When Login _fails_ it can be "_catastrophic_" to any app, getting it _right_ is _worth_ the [investment!](https://youtu.be/T9ikpoF2GH0)

<br />

> <sup>1</sup>The **_exception_** to this rule is **Online Banking**, which has _conditioned_ people to `expect` a **_short_ session** duration. This makes _perfect_ sense because financial services are _transactional_ by nature; people login to their Online Banking to perform a _specific_ task like "check balance" or "transfer money" which only takes a few clicks. _Very_ few people have a _reason_ to keep their Online Banking open for longer than a few minutes. 
_Automatically_ timing-out a session after 10 minutes of inactivity is the _appropriate_ UX.

# Story

As a "user" (_person using a web application_)
I want to be able to login _once_ and have the App _remember_ me for as long as I'm using the app.
So that I don't have to keep logging in each time I _use_ the App.

We don't want to _force_ people to constantly login to the App because it gets "old" _very_ fast and will result in people being less _effective_ with their time (_wasting time logging into apps is a "time tax" nobody wants to keep paying!_)

# Todo

We need a _sophisticated_ approach to session management that will ensure 
both _flawless_ UX and _excellent_ security for all people using our App on any device. 
These are the areas we need to cover:

+ [ ] Anonymous Sessions - for people who are curious about the App/Site 
but have not yet registered their email address to persist their interactions. 

+ [ ] Registration with Email address. 

+ [ ] Verification - email address is verified by clicking a link sent by email.

+ [ ] Re/Set Password - once the person has verified their email address we ask them to define a password so they can login again. This is the _same_ form to be used in the case where the person cannot _remember_ their password and wants to re-set it. (_all that changes is the copy_)

+ [ ] Login - the person logs into the App/Site using an email address and password. If either of these two are not present in the **`people`** table (_or invalid in the case when a password is incorrect_), then login will fail with the appropriate (_friendly_) message. If email and password are valid, show the page they were attempting to reach or their "dashboard".  

+ [ ] Logout - destroy the session on their machine/device and set the **`end_time`** in **`sessions`** table. 

Each one of these checklist items will need it's own issue/story with UX/UI flow & logic.
I will get these done shortly. ⏳ 

> If you are ever in any _doubt_ as to what/how we should implement sessions (_or anything else_) for Auth, Google is the ["_reference implementation_"](https://en.wikipedia.org/wiki/Reference_implementation) to consult.
if you are not _already_ using any Google Apps (G Suite, Gmail, Calendar, Drive, Docs, Meet, etc),
consider trying it out just for professional curiosity.

**Comment by nelsonic** [comment]
This is the next logical thing to tackle in Auth. I'm doing it today. 👍

**Comment by nelsonic** [comment]
Sessions working as expected:
![image](https://user-images.githubusercontent.com/194400/141379450-84ce26b0-6b3d-4038-a45d-21c8ec0b9733.png)

![image](https://user-images.githubusercontent.com/194400/141379460-455685b5-e6af-4dc0-bcd2-c2b5a4312fcf.png)

`session.end` updated in `AuthWeb.AuthController.logout/2` which in turn invokes `Auth.Session.end_session/1`
![image](https://user-images.githubusercontent.com/194400/141379378-9ca8ce8a-a0cd-421e-8025-060872705a4f.png)

**Comment by nelsonic** [comment]
PR: #159 assigned for review. :shipit:
