### ISSUE TITLE
[Epic] Multi-factor Authentication (MFA)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#33]
High value apps or those with sensitive personal data **_need_ extra security**.
We need to make time to investigate Multi-factor Authentication (MFA)
https://en.wikipedia.org/wiki/Multi-factor_authentication

# Todo

+ [ ] Investigate ***Open Source*** solutions
+ [ ] Investigate ***3***<sup>rd</sup> **Party** Solutions.
  + https://theappfactor.com/best-two-factor-authentication-apps
  + https://www.codementor.io/slavko/google-two-step-authentication-otp-generation-du1082vho
  > **Note**: we would **prefer** not use SMS-based solutions because:
    + A lot of people have SMS messages appear on their "lock screen" so if a person has physical access to the device (_e.g: a rogue employee_) they can access the token without detection!
    + SMS incur a cost without a corresponding security advantage over OTP apps.
+ [ ] Determine if there is a _free_ or _low-cost_ solution that does not compromise on security
  + [ ] If no free/low-cost solution exists, why not? (_is it a technical or intellectual property challenge?_)
+ [ ] Document/Share findings in a **`mfa-research.md`** file.

If you have time + curiosity to help on this, please comment below!

**Comment by joostmouw** [comment]
Dear Nelson,

For a university project we are looking for an open-source project where multiples challenges occur. We have seen the following issue at your project: https://github.com/dwyl/auth/issues/33. And we are able to actively contribute and help to resolve it!  

We would love to help you and we hope we can get in contact!

Kind regards,

A very motivated studygroup from the Vrije Universiteit Amsterdam

**Comment by nelsonic** [comment]
Hi @joostmouw thanks for showing interest in this issue. 👋 
We are in the process of re-writing this package to be more modular.
What do you have in mind in terms of contributing to multi-factor auth? 
If you can share your thoughts we take it from there.
Do you have much experience with **`Elixir`**?
If not, what _is_ your preferred programming language?

**Comment by joostmouw** [comment]
Hi Nelson,

First, sorry for the late reaction. We needed to get together to discuss what we can contribute to your project. Actually we are not very experienced with programming, so sorry for the misunderstanding. We found your project with the Multi-factor Authentication and we all feel very engaged with it. Cause nowadays it is more important than ever. So that's why we contacted you. We hope that we can help you out in any other way for this project. We named some examples for you: 
We can be the test group (UX) for the authentication.
We can do surveys around our campus so students can give their view on Multi-factor Authentication. 
We can spread a flyer (for contribution) next to the computer faculty for engaging more contributes for you.   

Hope there is a place for us in your team so we help you with this project!

**Comment by nelsonic** [comment]
@joostmouw don't worry delayed replies on GitHub we're all busy. 👍 
We _agree_ that multi-factor auth is very important. 🔐 

Are you and your colleagues studying a technical subject at VU? 
(_Don't worry if not. I studied [Accounting](https://www.linkedin.com/in/nelsonic) I think anyone can learn to code. It's just practice. Just trying to gauge how technical I should be in my communication. e.g. more/less jargon/explanation_)

> Out of curiosity _how/where_ did you discover @dwyl and this thread specifically? 
Did you just search Google?

We have 3 options for implementing MFA:
+ Use an existing library written in a _different_ programming language e.g:  [npmjs.com/package/otplib](https://www.npmjs.com/package/otplib)
+ Use a _existing_ library written in `Elixir/Erlang` if one is available.
+ Write out own library from scratch following the RFCs and reading code in other libraries.

**Comment by joostmouw** [comment]
@nelsonic We do not specifically study technical subjects within our course. More business analytics  specified on the digital ways and influences. So I think it would be great to keep the jargon as easy as possible ;)

We found your issue by google indeed. It part of our subject to participate in a open source group to help with an issue. So we could choose something within our own interest. That's why we contacted you. Also we are curious how Open Source Teams operate and what the big differences are with regular co-working teams. So we also have some questions for you about that. Which communication route do you prefer for these questions?    

About the implementing MFA, we will do some research and get back to you in one or two days.
