### ISSUE TITLE
Extract client_id from HTTP referer 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#55]
`auth_plug` sends the `client_id` to the `auth_url` when no valid JWT is found: [lib/auth_plug.ex#L167](https://github.com/dwyl/auth_plug/blob/b612845c62d7257c4a665f83faea3c31debacbbf/lib/auth_plug.ex#L167)
We need to _verify_ the `client_id` (_`decode_decrypt/1` followed by lookup in `apikeys`_)
and if the `client_id` is valid, use the `client_secret` to sign the JWT on successful authentication.

# Todo
+ [x] Extract the `client_id` from the HTTP `referer`
  + [x] Check if the `client_id` is valid _before_ displaying the "login buttons" page
    + [x] If `client_id` **not** valid, return a friendly Error: `401: AUTH_API_KEY not valid`
+ [x] Include the `client_id` in the `state` prop that gets sent to GitHub/Google
I checked and it's [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.4) compliant to have multiple question marks in a URL Query:
https://stackoverflow.com/questions/2924160/is-it-valid-more-than-one-question-mark-in-a-url
+ [x] Extract the the `client_id` from the `state` (_returned by Auth Provider_)
+ [x] Confirm that it's _still_ valid (_not altered by the Auth Provider > `decode_decrypt/1`_) 
+ [x] Lookup the `client_id` in `apikeys` 
+ [x] Use corresponding `client_secret` to sign JWT 
+ [x] Redirect back to original HTTP referer with JWT

With the completion of this issue Auth https://github.com/dwyl/app/issues/268 will be _fully_ functional!
Let's get it done!

**Comment by nelsonic** [comment]
![true](https://user-images.githubusercontent.com/194400/80473192-b1f73500-893d-11ea-87c1-edf4fec53da2.jpg)

**Comment by nelsonic** [comment]
Extracting the `client_id` from the URL query params works:
![image](https://user-images.githubusercontent.com/194400/80540603-89088b80-89a1-11ea-8861-856eeacc3d21.png)

**Comment by nelsonic** [comment]
This is working. ✅ 
See: #43
