### ISSUE TITLE
Register/Login with Email and Password

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#63]
There will _always_ be people who prefer to use an Email address and Password for Authentication for whatever reason. We need to give them a seamless experience.

# Todo

+ [x] Create a Simple form that has a single input field: `:email`
+ [x] The input should be semantic such that the browser will autocomplete the data:
```html
<input type="email" id="email" size="30" required autofocus placeholder="yourname@email.com">
```
FYI: this is an interesting article on placeholders: https://www.smashingmagazine.com/2018/06/placeholder-attribute (_I'm still using them!_)
+ [x] Store `referer` and `auth_client_id` as hidden form field **`state`** so we can redirect on success.
+ [x] Submit button copy: "Login / Register"
+ [x] Check if there is a person with the given email address.
  + [x] If the person exists **_and_ has verified** their email address, display the password prompt. (Login)
  + [x] If the person exists but has **not verified** send them an email reminding them to verify.
      + [x] Display message in UI saying "we have sent you an email to verify your address". #62
      + [x] When the person clicks the link in the verification email, display the password prompt.
+ [x] If the person **does not exist**, create them and then render the "Please verify" UI 
  > "please check your email and click the link to verify".
  + [x] Create a Password Form
+ [x] If password is correct redirect to the original `referer` using the `auth_client_secret` to sign the `JWT`

**Comment by nelsonic** [comment]
iPhone 6/7/8/SE aspect ratio (_the most popular iOS device aspect ratio_):
![image](https://user-images.githubusercontent.com/194400/80857200-2be23380-8c48-11ea-980d-1531d2be708e.png)

Need to tidy up the spacing. 📏

**Comment by nelsonic** [comment]
Removed padding from container and the spacing fixed itself:
![image](https://user-images.githubusercontent.com/194400/80857407-d73fb800-8c49-11ea-9f97-0dfaec77e8b8.png)

Very happy for _anyone_ `else` to tidy up styling, copy etc. (Post MVP).

**Comment by nelsonic** [comment]
browser validation:
![image](https://user-images.githubusercontent.com/194400/80857820-e4aa7180-8c4c-11ea-9633-66cccad6cea5.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/81044722-c773de00-8eac-11ea-8a22-1adaf95636ef.png)

![image](https://user-images.githubusercontent.com/194400/81044808-e96d6080-8eac-11ea-8cca-bdc6cd2004c0.png)

When I click the link this is what I see:
![image](https://user-images.githubusercontent.com/194400/81044106-93e48400-8eab-11ea-9edb-9a68bd482c51.png)

And in the database we can see that this record has been updated to `status=1` (verified)
![image](https://user-images.githubusercontent.com/194400/81044959-2b96a200-8ead-11ea-885b-9124234a59c9.png)

Verification of email address by link sent to email is working. ✅

**Comment by nelsonic** [comment]
Derp! Didn't mean to _close_ the issue. Still have to finish the password _setup_ stage. 🧑‍💻

**Comment by nelsonic** [comment]
<img width="1470" alt="registration-login-email-password-flow-diagram" src="https://user-images.githubusercontent.com/194400/81224631-e8891b80-8fdf-11ea-8e75-e3751d407b38.png">

[Edit this diagram](https://docs.google.com/presentation/d/1PUKzbRQOEgHaOmaEheU7T3AHQhRT8mhGuqVKotEJkM0/edit#slide=id.g7745f61495_0_0)

**Comment by nelsonic** [comment]
Register with Email+Password works:
![image](https://user-images.githubusercontent.com/194400/81236428-19c01680-8ff5-11ea-8689-839c9b6200b7.png)

Now to work on Login. ⏳

**Comment by nelsonic** [comment]
In case anyone is wondering _why_ I have split the register/login into two steps
1. input your email address
2. input your password
It's because several prominent UX-focussed apps/sites have reached the same conclusion:
It **reduces friction** and _increases_ security. Counterintuitively perhaps because we are not allowing people to simply tab to the next field and submit both email and password in a _single_ HTTP Request. But this helps mitigate phishing attacks and automated login attempts. 

Google:
![image](https://user-images.githubusercontent.com/194400/81267155-e786d700-903d-11ea-9b7b-d79cb15b8054.png)

Notice how they have the "eye" icon in the password field allowing people to view the password/passphrase they have entered: #65 

![image](https://user-images.githubusercontent.com/194400/81267222-02594b80-903e-11ea-8186-11390238ae82.png)

> Don't worry, this is not my _real_ password. (duh!)

Read: 
+ https://www.quora.com/Why-does-Gmail-use-two-separate-pages-for-logging-in-Why-not-let-users-enter-both-username-and-password-on-the-same-page
+ https://security.stackexchange.com/questions/85160/is-having-the-username-and-password-fields-on-different-pages-more-secure

AWS: https://signin.aws.amazon.com
![image](https://user-images.githubusercontent.com/194400/81267852-0a65bb00-903f-11ea-831c-4230645083c3.png)


Ebay:
![image](https://user-images.githubusercontent.com/194400/81266767-3c761d80-903d-11ea-9026-2c93bb8e3382.png)

Yahoo and Shopify:
![yahoo-shopify](https://user-images.githubusercontent.com/194400/81267814-f621be00-903e-11ea-8ef4-136f7266c1e8.png)

**Comment by nelsonic** [comment]
Password hashing is performed _transparently_ by `Fields.Password` using Argon2.
Specifically: [github.com/dwyl/fields/lib/helpers.ex#L10-L12](https://github.com/dwyl/fields/blob/fcacd3c7417a5418b7ca3cd13ac02c851cee1419/lib/helpers.ex#L10-L12)
The verification function is: `Argon2.verify_pass(password_plaintext, password_hash)`
which returns boolean `true` if the password matches or `false` if not.

**Comment by nelsonic** [comment]
This feature is _finally_ included in #43 assigned to @SimonLab for review. :shipit:

**Comment by nelsonic** [comment]
Shipped. 🚀 
There are _always_ enhancements https://github.com/dwyl/auth/issues we can add later. `#HelpWanted`
