### ISSUE TITLE
Update All Dependencies (Phoneix, Ecto, Fields, etc.)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#76]
Now that #43 and #75 are merged, we can update the dependencies to latest versions.

# Todo 

+ [x] Consult the list of dependencies that have updates on https://libraries.io/hex/auth
![image](https://user-images.githubusercontent.com/194400/81947362-5cd34880-95f8-11ea-9867-f50c8f7409ba.png)
+ [x] Update all dependencies and any necessary code.
+ [x] Create Pull Request
+ [x] Publish new version of `auth` to Hex.pm so that the badge will reflect the update.

We should do this update _after_ https://github.com/dwyl/phoenix-chat-example/issues/38 so we get some practice. 
The _reason_ we create examples is so that we can get _practice_ with our craft/tools. 
It also serves as a more generic intro to a given topic (e.g. Learning Phoenix) that members of the _extended_ Elixir community can benefit from. In general, I find that once I've done an upgrade to _one_ project it's easier to replicate it the second time.

**Comment by nelsonic** [comment]
Added `P2` because I feel that we _really_ want to keep this up-to-date to show it's _maintained_. 💭

**Comment by SimonLab** [comment]
Following the upgrade guide for Phoenix 1.5: https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f

**Comment by nelsonic** [comment]
@SimonLab thanks for PR #79 ✅

**Comment by nelsonic** [comment]
Updated Package published to https://hex.pm/packages/auth/1.2.2 📦

**Comment by nelsonic** [comment]
Waiting for Libraries.io to update ... [![Libraries.io dependency status](https://img.shields.io/librariesio/release/hex/auth?logoColor=brightgreen&style=flat-square)](https://libraries.io/hex/auth) ⏳

**Comment by nelsonic** [comment]
Done. ✅ 
(thanks @SimonLab!)
