### ISSUE TITLE
UX Enhancement: Add autofocus to password_input fields

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#80]
At present we do not have the `autofocus` attribute in our password prompt:
https://github.com/dwyl/auth/blob/946f6ba58844798b32b2a81f5b1a246a3b396549/lib/auth_web/templates/auth/password_prompt.html.eex#L6-L7
Or password create:
https://github.com/dwyl/auth/blob/946f6ba58844798b32b2a81f5b1a246a3b396549/lib/auth_web/templates/auth/password_create.html.eex#L6-L8

Having recently discovered how to do it: https://github.com/dwyl/learn-phoenix-framework/issues/138
I feel this is a worthwhile enhancement that can be added to speed up the UX on both password creation and password prompt forms. 

# Todo

+ [ ] add `autofocus: "true"` to the `password_input` in `lib/auth_web/templates/auth/password_prompt.html.eex#L6-L7`
+ [ ] add `autofocus: "true"` to the `password_input` in `/lib/auth_web/templates/auth/password_create.html.eex#L6-L8`
+ [ ] Create Pull Request referencing this issue.

This is a perfect "first contribution" for someone new to the team/project.
