### ISSUE TITLE
Create Seeds Script to Create Default Roles and Permissions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#86]
As noted in https://github.com/dwyl/auth/issues/82#issuecomment-662993834 we have **7 `default` roles**:

| **`id`** | **`name`** | **`desc`** | `person_id` |
| -------- | ---------- | ---------- | ----------- |
| `1` | superadmin | Can **`CREATE`** new roles. Can **`CREATE`**, **`UPDATE`** and **`DELETE`** Any content. Can **`PURGE`** deleted items. Can "ban" any user including people with "Admin" Role. | 1 |
| `2` | admin | Can **create** new roles and **assign** existing roles. Can **`CREATE`**, **`UPDATE`** and **`DELETE`** any content. Can "ban" any user except people with "admin" Role. Can see deleted content and un-delete it. Cannot _purge_ deleted. This guarantees audit-trail. | 1 | 
| `3` | editor | Can **`CREATE`** and **`UPDATE`** _Any_ content. Can **"`DELETE`"** content. Cannot _see_ deleted content. | 1 |
| `4` | creator | Can **`CREATE`** content. Can **`UPDATE`** their _own_ content. Can **`DELETE`** their _own_ content. | 1 |
| `5` | commenter | Can **`COMMENT`** on content that has commenting enabled. | 1 |
| `6` | subscriber | Can **`SUBSCRIBE`** to receive updates (e.g: newsletter), but has either not verified their account or has made negative comments and is therefore _not_ allowed to comment. | 1 |
| `7` | banned | Can login and see their past content. Cannot create any new content. Can see the _reason_ for their banning (_which the Admin has to write when performing the "ban user" action. usually linked to a specific action the person performed like a particularly unacceptable comment._) | 1 | 

# Todo 

+ [x] write a script to create both the roles and permissions during `mix ecto.setup`.
+ [x] Create all `default` roles + permissions, inspired by: https://wordpress.org/support/article/roles-and-capabilities
+ [x] Create all `default` roles

I expect this task to take a couple of hours.
But I'm going to install Wordpress on my `localhost` _first_ and view how they have setup the permissions.
Related to #27 / #31

**Comment by nelsonic** [comment]
Default roles created: 
![image](https://user-images.githubusercontent.com/194400/88463571-9b646980-ceab-11ea-8343-2df9b2baa2ac.png)

**Comment by nelsonic** [comment]
Created in #85 > https://github.com/dwyl/auth/blob/master/priv/repo/default_roles.json ✅
