### ISSUE TITLE
ADMIN: Display a Table of Authenticated People

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#93]
At present we do not have an "Admin View" that allows the administrator of the **`Auth`** App to see all the people who have authenticated with the App; we haven't _needed_ it until now.

As part of the addition o Role Based Access Control (**RBAC**) we need a way of visualising exactly who has which role(s) in the system. Ideally this view should also allow us to quickly **`grant`** (_new_) and **`revoke`** (_existing_) roles for the people.

## Todo

Create
+ [x] `/people` route only visible to people with **`admin`** (_or **`superadmin`**_) role.
+ [x] `people_controller.ex` to handle the request
+ [x] `people_view.ex` for any helper functions
+ [x] `/people/index.html.eex` template for the HTML+CSS+JS
+ [x] Tests!

I'm thinking of using DataTables https://github.com/DataTables/DataTables for this.
https://www.datatables.net
![image](https://user-images.githubusercontent.com/194400/90965963-13cb4400-e4c5-11ea-9c87-130feff8fb22.png)
I know it's JQuery and that's not _fashionable_. But According to NPM Trends this is _still_ the most popular way of dynamically displaying tabular data.
https://www.npmtrends.com/datatables-vs-dynatable-vs-footable-vs-tabulator-vs-fancygrid
Yes, there is https://github.com/adazzle/react-data-grid for the Küel Kids who use React. 
But I just did a quick read of the features/code and it doesn't offer any benefit over DataTables. 🤷‍♂️

**Comment by nelsonic** [comment]
With **`status`** and **`roles`**:
![image](https://user-images.githubusercontent.com/194400/90990296-5a3da300-e598-11ea-9698-fe94d25e8812.png)

**Comment by nelsonic** [comment]
Works. for now only viewable by admin. ✅
