### ISSUE TITLE
Create "App" Schema/CRUD then Link API Keys and Roles

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#95]
While preparing to create the function that returns the List of Roles for an App https://github.com/dwyl/rbac/issues/3,
I noted that we don't actually _have_ the concept of different "Applications" in Auth right now ... 🙄 
Our original idea for the Auth API Key #42 was to allow people to run the DWYL App on their `localhost` without having to setup an Auth server. That goal was achieved. ✅ 
However if we want Auth to be a turnkey multi-app auth solution, we need the concept of "Apps". 

Gonna transfer a few of the fields over from the API key specifically:

+ name
+ description
+ url
+ person_id

https://github.com/dwyl/auth/blob/fafc5e059d65de420b4d99bf1d15ac45a3bcda12/lib/auth/apikey.ex#L9-L16

# Todo

+ [x] Create **`App`** schema 
  + [x] belongs_to `person`
  + [x] name
  + [x] description
  + [x] url
  + [x] status
  + [x] has_many `apikeys`

+ [x] Migrate data from API Key to App
+ [x] Update `apikeys` schema to have a `belongs_to` so the `app` owns the key.

Once this is done we will need to:

+ [x] add `app_id` to Roles so that we can have distinct roles for different applications 
and can create unlimited Apps/Roles.  #108 
  > **Note**: no need for a migration on this, just edit the original Roles create migration/schema as it's all part of the same PR #85 

+ [x] Add `app_id` to Roles table in `/people` (index view) and `/people/:id`

**Comment by nelsonic** [comment]
After reading through the code that creates API keys, I've realised that it's a bit more work than **`T1h`** so I have revised _up_ my estimate. I think think this feature and the corresponding refactor/rework will take me a day. It's at _least_ a couple of hundred lines of code and tests need to be updated/re-written too ... ⏳

**Comment by nelsonic** [comment]
```sh
mix phx.gen.html Ctx App apps person_id:references:people name:binary description:binary url:binary status:references:status apikey_id:references:api end:naive_datetime
```

Default UI for creating an App:
![image](https://user-images.githubusercontent.com/194400/91861711-0a7c6d00-ec65-11ea-92fb-55376197d2cc.png)

Obviously this UI is hideous so I'm going to tidy it up.

**Comment by nelsonic** [comment]
The "end" field is not relevant for now, so this is what the /apps/new form looks like:
![image](https://user-images.githubusercontent.com/194400/91863118-abb7f300-ec66-11ea-82ba-ceb26a77eae6.png)

**Comment by nelsonic** [comment]
This issue is complete. #85
